# Site settings
title: Timothy Basanov
email: timofey.basanov@gmail.com
url: "http://timothybasanov.com" # the base hostname & protocol for your site
github_username:  timothybasanov
timezone: America/Los_Angeles
