# Site settings
title: Timothy Basanov
email: timofey.basanov@gmail.com
url: "https://timothybasanov.com" # the base hostname & protocol for your site
github_username: timothybasanov
twitter_username: timothybasanov 

exclude: [Gemfile, README.md, '*.sublime-*', CNAME]
safe: true
timezone: America/Los_Angeles

kramdown: 
  input: GFM

redcarpet:
  extensions: [smart]

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!--more-->

theme: jekyll-theme-cayman