# Site settings
title: Timothy Basanov's home page
email: timofey.basanov@gmail.com
url: "https://timothybasanov.com" # the base hostname & protocol for your site
github_username: timothybasanov
twitter_username: timothybasanov 
timezone: America/Los_Angeles

exclude: [Gemfile, README.md, '*.sublime-*', CNAME]
kramdown:
  input: GFM
